Algoritmo "CONTADORAEXEMPLO"
// Disciplina   : [Lógica de Programação com Javasript]
// Professor   : Jailson 
// Descrição   : Fazer ir até 9
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2022
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora<10 faca
escreval(contadora)
contadora<- contadora+1
fimenquanto

Fimalgoritmo