Algoritmo "NUMEROSIMPAR"
// Disciplina   : [Lógica de Programação com Javasript]
// Professor   : Jailson 
// Descrição   : Mostrar números de 1 a 20 que são ímpar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/04/2022
Var
// Seção de Declarações das variáveis 
numero: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
enquanto numero<21 faca
se (numero mod 2)=1 entao
Escreval(numero)
fimse
numero<- numero+1
fimenquanto


Fimalgoritmo